
# Project ID is the first line and is required
project_id = "krupkuoyijlnamjnheau"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 9999

[storage]
enabled = true
port = 5000

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = false

[edge_functions]
enabled = true

[functions.ai-assistant]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.run-scheduled-tasks]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
